{{- if .Values.operator.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  channel: {{ .Values.operator.channel }}
  installPlanApproval: {{ .Values.operator.installPlanApproval }}
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}