---
kind: Secret
apiVersion: v1
metadata:
  name: keycloak-admin
stringData:
  username: {{ .Values.keycloak.bootstrapAdmin.username }}
  password: {{ .Values.keycloak.bootstrapAdmin.password }}
type: Opaque
